spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  mail:
    port: 25
    username: pratsanyou02@gmail.com
    password: Ashapal1@
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      org:
        hibernate:
          dialect:
            MySQLDialect: org.hibernate.dialect.MySQLDialect




#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect:org.hibernate.dialect.MySQLDialect

server:
  port: 9090

logging:
  level:
    org.springframework: ERROR
    com.kirana: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log


